osx_image: xcode7.3

language: objective-c

script:
- set -o pipefail && xcodebuild -workspace Reductio.xcworkspace -scheme Reductio -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s' GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES analyze build test | xcpretty -c
- pod lib lint --quick

after_success:
- bash <(curl -s https://codecov.io/bash)
